/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eminetokmak
 */
public class Giris extends javax.swing.JFrame {

    KullaniciOperation islemler = new KullaniciOperation();
    HakemOperation hakemislem=new HakemOperation();
    OKBoperation OKBislem =new OKBoperation();
    public Giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullaniciID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        mesaj = new javax.swing.JLabel();
        Giris = new javax.swing.JButton();
        hakem_giris = new javax.swing.JButton();
        okb_giris = new javax.swing.JButton();
        kul_olustur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kullaniciID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Kullanıcı Id:");

        jLabel2.setText("Şİfre");

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        mesaj.setForeground(new java.awt.Color(255, 0, 0));

        Giris.setText("Yazar Girişi");
        Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisActionPerformed(evt);
            }
        });

        hakem_giris.setText("Hakem Girişi");
        hakem_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakem_girisActionPerformed(evt);
            }
        });

        okb_giris.setText("OKB Girişi");
        okb_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okb_girisActionPerformed(evt);
            }
        });

        kul_olustur.setText("Kullanıcı Oluştur");
        kul_olustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kul_olusturActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullaniciID, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(pass))
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Giris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hakem_giris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okb_giris))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(kul_olustur)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullaniciID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Giris)
                    .addComponent(hakem_giris)
                    .addComponent(okb_giris))
                .addGap(18, 18, 18)
                .addComponent(kul_olustur)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisActionPerformed
       
        mesaj.setText("");
        String kullanici_id =this.kullaniciID.getText();
        String sifre= new String(pass.getPassword());
        
        boolean girisbasarili=islemler.GirisYap(kullanici_id,sifre);
        
        if(girisbasarili){
       //YazarEkran yazarekran =new YazarEkran(this,true);
            setVisible(false);
            new YazarEkran(kullanici_id).setVisible(true);
            //System.exit(0);
        }else{
        
        mesaj.setText("Giriş Başarısız");
        }
    }//GEN-LAST:event_GirisActionPerformed

    private void kullaniciIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciIDActionPerformed

    private void hakem_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakem_girisActionPerformed
      mesaj.setText("");
        String kullanici_id =this.kullaniciID.getText();
        String sifre= new String(pass.getPassword());
        
        boolean girisbasarili=hakemislem.HakemGirisYap(kullanici_id,sifre);
        
        if(girisbasarili){
            //HakemEkrani hakemekran =new HakemEkrani(this,true);
            setVisible(false);
            
           new HakemEkrani(kullanici_id).setVisible(true);
           // System.exit(0);
        }else{
        
        mesaj.setText("Giriş Başarısız");
        }
    }//GEN-LAST:event_hakem_girisActionPerformed

    private void kul_olusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kul_olusturActionPerformed
     KullaniciOlustur yenikullanici =new KullaniciOlustur(this,true);
            setVisible(false);
            yenikullanici.setVisible(true);
            System.exit(0);
    }//GEN-LAST:event_kul_olusturActionPerformed

    private void okb_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okb_girisActionPerformed
         mesaj.setText("");
        String kullanici_id =this.kullaniciID.getText();
        String sifre= new String(pass.getPassword());
        
        boolean girisbasarili=OKBislem.OKBGirisYap(kullanici_id,sifre);
        
        if(girisbasarili){
            
            OKBekran okbeKRAN =new OKBekran(this,true);
            setVisible(false);
            
            okbeKRAN.setVisible(true);
            System.exit(0);
        }else{
        
        mesaj.setText("Giriş Başarısız");
    }//GEN-LAST:event_okb_girisActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Giris;
    private javax.swing.JButton hakem_giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kul_olustur;
    private javax.swing.JTextField kullaniciID;
    private javax.swing.JLabel mesaj;
    private javax.swing.JButton okb_giris;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
